# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-31 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0005_delete_recentmatches'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('player1', models.CharField(max_length=255, null=True)),
                ('player2', models.CharField(max_length=255, null=True)),
                ('player3', models.CharField(max_length=255, null=True)),
                ('player4', models.CharField(max_length=255, null=True)),
                ('player5', models.CharField(max_length=255, null=True)),
                ('player6', models.CharField(max_length=255, null=True)),
                ('player7', models.CharField(max_length=255, null=True)),
                ('player8', models.CharField(max_length=255, null=True)),
                ('player9', models.CharField(max_length=255, null=True)),
                ('player10', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'matches',
            },
        ),
        migrations.RemoveField(
            model_name='userprofile1',
            name='leagues',
        ),
        migrations.AddField(
            model_name='league',
            name='password_status',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='league',
            name='skill_level',
            field=models.CharField(blank=True, default='BZ', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile1',
            name='steam_id',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='matches',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tether.League'),
        ),
    ]
