# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-31 07:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0006_auto_20170331_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='owner',
        ),
    ]
