# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-27 03:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('skill_level', models.CharField(max_length=255)),
                ('members', models.CharField(max_length=255)),
                ('slug', models.SlugField(default='', unique=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'league',
            },
        ),
        migrations.CreateModel(
            name='RecentMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_level', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('hero_id', models.IntegerField()),
                ('result_wl', models.BooleanField()),
                ('kda', models.FloatField()),
                ('gpm', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Recent matches',
                'db_table': 'recent_matches',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255)),
                ('steam_id', models.IntegerField(blank=True, editable=False, null=True, unique=True)),
                ('win_rate', models.DecimalField(decimal_places=2, default='0000000000', max_digits=10)),
                ('average_gpm', models.DecimalField(decimal_places=2, default='000000', max_digits=6)),
                ('league_rank', models.CharField(default='Bronze', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profile',
            },
        ),
        migrations.AddField(
            model_name='recentmatches',
            name='steam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tether.UserProfile'),
        ),
    ]
