# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-28 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0002_matches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matches',
            name='player1',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='player10',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='player2',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='player3',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='player4',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='player5',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='player6',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='player7',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='player8',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='matches',
            name='player9',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
