# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-23 23:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
