# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-10 08:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leagues', '0002_auto_20170109_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='league_id',
        ),
    ]
