# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2017-03-08 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tether', '0090_userprofile1_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile1',
            name='recent_matches',
        ),
    ]
